name: mmovie
description: monfadev movie.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  envied: ^0.3.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  freezed_annotation: ^2.2.0
  pretty_dio_logger: ^1.1.1

dev_dependencies:
  freezed: ^2.3.2
  envied_generator: ^0.3.0
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/